# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker', models.IntegerField(default=0)),
                ('warden', models.IntegerField(default=0)),
                ('gym_vp', models.IntegerField(default=0)),
                ('asst_reg', models.IntegerField(default=0)),
                ('sub_thesis', models.IntegerField(default=0)),
                ('librarian', models.IntegerField(default=0)),
                ('online_cc', models.IntegerField(default=0)),
                ('cc_in', models.IntegerField(default=0)),
                ('faculty', models.IntegerField(default=0)),
                ('dept_workshop', models.IntegerField(default=0)),
                ('hod', models.IntegerField(default=0)),
                ('accounts_head', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('hostel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='checkbox',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.credentials'),
        ),
    ]
