# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkbox',
            old_name='student',
            new_name='stud',
        ),
    ]
