# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20161114_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkbox',
            name='name',
        ),
        migrations.AddField(
            model_name='credentials',
            name='accounts_head',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='asst_reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='caretaker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='cc_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='dept_workshop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='faculty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='gym_vp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='hod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='librarian',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='online_cc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='sub_thesis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='warden',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='checkbox',
        ),
    ]
